/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Message.proto */

#ifndef PROTOBUF_C_Message_2eproto__INCLUDED
#define PROTOBUF_C_Message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _FILEDATA FILEDATA;


/* --- enums --- */


/* --- messages --- */

struct  _FILEDATA
{
  ProtobufCMessage base;
  char* m_pCmdBuf;
  char* m_pFileNameBuf;
  char* m_pFileDataBuf;
  protobuf_c_boolean has_m_uiFileSize;
  uint32_t m_uiFileSize;
};
#define FILE__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file__data__descriptor) \
    , NULL, NULL, NULL, 0, 0 }


/* FILEDATA methods */
void   file__data__init
                     (FILEDATA         *message);
size_t file__data__get_packed_size
                     (const FILEDATA   *message);
size_t file__data__pack
                     (const FILEDATA   *message,
                      uint8_t             *out);
size_t file__data__pack_to_buffer
                     (const FILEDATA   *message,
                      ProtobufCBuffer     *buffer);
FILEDATA *
       file__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file__data__free_unpacked
                     (FILEDATA *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FILEDATA_Closure)
                 (const FILEDATA *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor file__data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Message_2eproto__INCLUDED */
