/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_Message_2eproto__INCLUDED
#define PROTOBUF_C_Message_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _FILEDATA FILEDATA;


/* --- enums --- */


/* --- messages --- */

struct  _FILEDATA
{
  ProtobufCMessage base;
  char *p_cmd_buf;
  char *p_data_buf;
};
#define FILE__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file__data__descriptor) \
    , NULL, NULL }


/* FILEDATA methods */
void   file__data__init
                     (FILEDATA         *message);
size_t file__data__get_packed_size
                     (const FILEDATA   *message);
size_t file__data__pack
                     (const FILEDATA   *message,
                      uint8_t             *out);
size_t file__data__pack_to_buffer
                     (const FILEDATA   *message,
                      ProtobufCBuffer     *buffer);
FILEDATA *
       file__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file__data__free_unpacked
                     (FILEDATA *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FILEDATA_Closure)
                 (const FILEDATA *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor file__data__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_Message_2eproto__INCLUDED */
