/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Message.pb-c.h"
void   file__data__init
                     (FILEDATA         *message)
{
  static const FILEDATA init_value = FILE__DATA__INIT;
  *message = init_value;
}
size_t file__data__get_packed_size
                     (const FILEDATA *message)
{
  assert(message->base.descriptor == &file__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file__data__pack
                     (const FILEDATA *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file__data__pack_to_buffer
                     (const FILEDATA *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FILEDATA *
       file__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FILEDATA *)
     protobuf_c_message_unpack (&file__data__descriptor,
                                allocator, len, data);
}
void   file__data__free_unpacked
                     (FILEDATA *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor file__data__field_descriptors[4] =
{
  {
    "m_pCmdBuf",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FILEDATA, m_pCmdBuf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "m_pFileNameBuf",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FILEDATA, m_pFileNameBuf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "m_pFileDataBuf",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FILEDATA, m_pFileDataBuf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "m_uiFileSize",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FILEDATA, has_m_uiFileSize),
    offsetof(FILEDATA, m_uiFileSize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file__data__field_indices_by_name[] = {
  0,   /* field[0] = m_pCmdBuf */
  2,   /* field[2] = m_pFileDataBuf */
  1,   /* field[1] = m_pFileNameBuf */
  3,   /* field[3] = m_uiFileSize */
};
static const ProtobufCIntRange file__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor file__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FILE_DATA",
  "FILEDATA",
  "FILEDATA",
  "",
  sizeof(FILEDATA),
  4,
  file__data__field_descriptors,
  file__data__field_indices_by_name,
  1,  file__data__number_ranges,
  (ProtobufCMessageInit) file__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
